const registry = require('../skill_registry');

async function delegate(instructions, targetSkillName, context) {
  try {
    if (!context || !context.workspace || !context.user) {
       return { error: "Missing required execution context for delegation." };
    }

    const { workspace, user } = context;
    const targetSkill = registry.getSkill(targetSkillName);

    if (!targetSkill) {
      return { 
        error: `Delegation failed. Target skill '${targetSkillName}' does not exist.` 
      };
    }

    // To avoid circular dependency loading at boot, we lazy load the runner here
    const SkillRunner = require('../skill_runner');
    const runner = new SkillRunner(require('../config'));

    console.log(`[doom-agent] Delegating task to sub-agent: ${targetSkillName}`);
    
    // We pass the instructions as the "user message" for the sub-skill
    // Using a blank memory context since it's an isolated sub-task
    const result = await runner.run(
      targetSkill, 
      instructions, 
      null, // historyContext
      workspace, 
      user
    );

    return { result };

  } catch (error) {
    console.error('[doom-agent][delegate] Error:', error);
    return { error: error.message };
  }
}

/**
 * Returns the tool definition for the LLM prompt.
 */
function getDefinition() {
  return `
Tool: delegate
Description: Pauses the current skill and spins up an entirely separate, specialized AI agent (a 'skill') to perform a complex sub-task for you. Use this when the user asks for a complex goal that requires a different area of expertise (like asking 'write-blog' to write, or 'geo-audit' to analyze).
Parameters:
  - instructions (string): A highly detailed description of exactly what the target skill needs to do. Provide all context it will need.
  - target_skill (string): The exact folder name of the skill you want to invoke (e.g. 'write-blog', 'rag-query').
Returns: The final output generated by the specialized skill.
`;
}

module.exports = {
  delegate: {
    execute: delegate,
    definition: getDefinition()
  }
};
